"""gen_import_stubs.py - make the bulk DLL linkable.

The Ghidra bulk references the Win32 / DirectX / Miles imports of functions the
harness does not test (PostMessageA, DirectDrawCreate, AIL_*, ...).  The rebuild
does not provide those - in a real reimplementation they come from the system
DLLs - so they are aliased to one shared stub with the linker's
`/alternatename`.

The stubs are a *harness* device, not part of the rebuild: a function under test
that actually called Windows would jump through a NULL pointer and crash.  That is
exactly why tools/verify.py only exercises functions whose imports resolve
properly (the allocators, the fread wrappers, the small pure helpers).

    python tools/gen_import_stubs.py            # reads build/_ghidra_link.log
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = ROOT / "build" / "_ghidra_link.log"
OUTFILE = ROOT / "harness" / "import_stubs.c"


def main() -> int:
    if not LOG.exists():
        raise SystemExit(f"{LOG} missing - run harness/build_dlls.bat once so the linker lists them")
    text = LOG.read_text(encoding="latin1", errors="replace")
    # LNK2019 lines: `... simbolo esterno <SYM> non risolto ...` (locale wording varies)
    # wording-agnostic: the diagnostics are localised ("simbolo esterno" /
    # "external symbol"), so match the marker and take the token after it
    symbols = set()
    marker = re.compile(r"(?:simbolo\s+esterno|external\s+symbol)\s+([^\s:]+)")
    for line in text.splitlines():
        if "LNK2001" not in line and "LNK2019" not in line:
            continue
        for m in marker.finditer(line):
            symbols.add(m.group(1))
    if not symbols:
        print("no unresolved imports in the link log - nothing to stub")
        return 0

    lines = [
        "/* generated by tools/gen_import_stubs.py - do not edit */",
        "/* One shared stub for every unresolved DLL import, aliased with",
        "   /alternatename.  Harness device only: see the header of the generator. */",
        "",
        "void *__groove_import_stub = 0;",
        "",
    ]
    for sym in sorted(symbols):
        lines.append(f'#pragma comment(linker, "/alternatename:{sym}=__groove_import_stub")')
    OUTFILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTFILE.name} with {len(symbols)} import stubs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
