"""make_getters.py - generate address-keyed accessors for the harness DLLs.

The two DLLs hold the same globals under different names (the hand ports use the
IDA names like `byte_6D9858`, the Ghidra bulk uses Ghidra's `DAT_006D9858`), so a
shared wrapper cannot name them.  Keying the accessors by *address* solves that:
both sides expose `wh_get_006D9858()`, and tools/verify.py never has to know a
symbol name.

    python tools/make_getters.py            # writes harness/getters_ghidra.c
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src_generated"

# (address, accessor return type, element type, count)
TARGETS = [
    ("006D9858", "unsigned char", "unsigned char", 1),
    ("006D94E8", "unsigned char", "unsigned char", 1),
    ("00581158", "int", "int", 1),
    ("00586408", "int", "int", 1),
    ("0058640C", "int", "int", 1),
    ("00584644", "int", "int", 1),
    ("00586420", "int", "int", 1),
    ("00583740", "int", "int", 1),
    ("0058226C", "unsigned int", "unsigned int", 0x100),
    ("005821E0", "unsigned int", "unsigned int", 0x0F),
    ("005846EC", "unsigned int", "unsigned int *", 1),
    ("00581154", "unsigned int", "unsigned int", 1),   # triangle material table base
    ("006DA330", "unsigned int", "unsigned int", 1),   # WFPC flags (dword_6DA330)
    ("006D7C61", "unsigned char", "unsigned char", 1), # greyscale switch (dword_6D7C60+1)
    ("006DA320", "unsigned int", "unsigned int", 1),   # set to 100 by the MAP loader
    ("006DA328", "unsigned int", "unsigned int", 1),   # optional final dword / default 200
    ("00586584", "unsigned int", "unsigned int", 1),   # primary heap cursor
    ("00586588", "int", "int", 1),                     # primary heap remaining
    ("0058656C", "unsigned int", "unsigned int", 1),   # secondary heap cursor
    ("00586570", "int", "int", 1),                     # secondary heap remaining
]


def load_symbols() -> tuple[dict[int, str], dict[int, int]]:
    """address -> the name the generated globals use for it."""
    path = OUT / "symbols.csv"
    if not path.exists():
        raise SystemExit(f"{path} missing - run tools/make_bulk.py first")
    out: dict[int, str] = {}
    sizes: dict[int, int] = {}
    with path.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            a = int(row["address"], 16)
            out[a] = row["name"]
            sizes[a] = int(row["size"])
    return out, sizes


def main() -> int:
    symbols, sizes = load_symbols()
    lines = [
        "/* generated by tools/make_getters.py - do not edit */",
        "/* Address-keyed accessors over the Ghidra-side globals.  The hand side",
        "   defines the same function names over its own globals, so verify.py can",
        "   read either DLL without knowing a single symbol name. */",
        '#include "ghidra_shim.h"',
        '#include "ghidra_globals.h"',
        "",
        "#define WH_EXPORT __declspec(dllexport)",
        "",
    ]
    missing = []
    for addr, ret, elem, _count in TARGETS:
        name = symbols.get(int(addr, 16))
        size = sizes.get(int(addr, 16), 4)
        if name is None:
            missing.append(addr)
            continue
        if elem.endswith("*"):
            # a slot holding a pointer: hand back its address
            lines.append(f"WH_EXPORT {ret} **wh_get_{addr}(void) {{ return &{name}; }}")
        elif size > 4:
            # an array: the name decays to its address
            lines.append(f"WH_EXPORT {ret} *wh_get_{addr}(void) {{ return {name}; }}")
        else:
            # a scalar: the accessor must return its ADDRESS, not its value
            lines.append(f"WH_EXPORT {ret} *wh_get_{addr}(void) {{ return &{name}; }}")
    (ROOT / "harness" / "getters_ghidra.c").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote harness/getters_ghidra.c with {len(TARGETS) - len(missing)} accessors")
    if missing:
        print("  NOT FOUND in the generated globals (function excluded?): " + ", ".join(missing))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
