/* generated by tools/make_getters.py - do not edit */
/* Address-keyed accessors over the Ghidra-side globals.  The hand side
   defines the same function names over its own globals, so verify.py can
   read either DLL without knowing a single symbol name. */
#include "ghidra_shim.h"
#include "ghidra_globals.h"

#define WH_EXPORT __declspec(dllexport)

WH_EXPORT unsigned char *wh_get_006D9858(void) { return &DAT_006d9858; }
WH_EXPORT unsigned char *wh_get_006D94E8(void) { return &DAT_006d94e8; }
WH_EXPORT int *wh_get_00581158(void) { return &DAT_00581158; }
WH_EXPORT int *wh_get_00586408(void) { return &DAT_00586408; }
WH_EXPORT int *wh_get_0058640C(void) { return &DAT_0058640c; }
WH_EXPORT int *wh_get_00584644(void) { return &DAT_00584644; }
WH_EXPORT int *wh_get_00586420(void) { return &DAT_00586420; }
WH_EXPORT int *wh_get_00583740(void) { return &DAT_00583740; }
WH_EXPORT unsigned int *wh_get_0058226C(void) { return &DAT_0058226c; }
WH_EXPORT unsigned int *wh_get_005821E0(void) { return &DAT_005821e0; }
WH_EXPORT unsigned int **wh_get_005846EC(void) { return &DAT_005846ec; }
WH_EXPORT unsigned int *wh_get_00581154(void) { return &DAT_00581154; }
WH_EXPORT unsigned int *wh_get_006DA330(void) { return &DAT_006da330; }
WH_EXPORT unsigned char *wh_get_006D7C61(void) { return &DAT_006d7c61; }
WH_EXPORT unsigned int *wh_get_006DA320(void) { return &DAT_006da320; }
WH_EXPORT unsigned int *wh_get_006DA328(void) { return &DAT_006da328; }
WH_EXPORT unsigned int *wh_get_00586584(void) { return &DAT_00586584; }
WH_EXPORT int *wh_get_00586588(void) { return &DAT_00586588; }
WH_EXPORT unsigned int *wh_get_0058656C(void) { return &DAT_0058656c; }
WH_EXPORT int *wh_get_00586570(void) { return &DAT_00586570; }
